### ISSUE TITLE
Batch connection (autoconnect) not working after adapter is turned off/on :: issue

### ISSUE THREAD

**Issue by droideveloper1996** [weliem/blessed-android#110] opened 2021-08-18 09:06 UTC
Recently I have noticed that once I turn off my Bluetooth I can see callback getting fired onBluetoothAdapterStateChanged()
and I keep on waiting for the connection to happen again but seems the connection does not happen. I even tried to create a Bluetooth peripheral then creating a new batch and starting the connection even this does not work for me.
The only way to make it work is to restart my service i.e force stop my application. 

Seems like Bluetooth adapter when restarted the old object address is not refrenced.
Any Clue how to fix this.Suggestions and help would be appreciated.

  @Override
        public void onBluetoothAdapterStateChanged(int state) {
            super.onBluetoothAdapterStateChanged(state);
            if(BluetoothAdapter.STATE_ON==state){
                Log.d(TAG, "BluetoothEnabled");
                Set<String> devices = App.getRooms().keySet();
                batch.clear();
                for (String linkedMac : devices) {
                    Log.d("TAGMac", linkedMac);
                    BluetoothPeripheral peripheral = bluetoothCentralManager.getPeripheral(linkedMac);
                    batch.put(peripheral, peripheralCallback);
                }
                bluetoothCentralManager.autoConnectPeripheralsBatch(batch);
            }
            if(BluetoothAdapter.STATE_OFF==state){
                Log.d(TAG,"BluetoothDisabled");
            }
        }

**Comment by weliem** [comment] 2021-08-18 18:39
Can you add a log so I can see what is happening?

**Comment by droideveloper1996** [comment] 2021-08-31 05:56
I did somewhat this  whenever Bluetooth is turned off in onBluetoothAdapterStateChanged call back I create a fresh batch connection and this one works perfectly fine for me. If I try to use the existing BluetoothCentralManager instance it does not works but on creating new Object it works fine. I am bit skepticle how Blessed handles the previous instance.


  @Override
        public void onBluetoothAdapterStateChanged(int state) {
            super.onBluetoothAdapterStateChanged(state);

            if (BluetoothAdapter.STATE_ON == state) {
                ArrayList<BluetoothPeripheral> peripheralsList = (ArrayList<BluetoothPeripheral>) 
                bluetoothCentralManager.getConnectedPeripherals();
                for (BluetoothPeripheral pe : peripheralsList) {
                    System.out.println("This is still connected"+ pe.getAddress());
                }

                Log.d(TAG, "BluetoothEnabled");
                bluetoothCentralManager = new BluetoothCentralManager(getApplicationContext(), callback, handler);
                bluetoothCentralManager.autoConnectPeripheralsBatch(batch);

                peripheralsList = (ArrayList<BluetoothPeripheral>) bluetoothCentralManager.getConnectedPeripherals();
                for (BluetoothPeripheral pe : peripheralsList) {
                    System.out.println("This is still connected"+ pe.getAddress());
                }
//                peripheralsList.
//                Set<String> devices = App.getRooms().keySet();
//                batch.clear();
//                for (String linkedMac : devices) {
//                    Log.d("MacAddress in enabling adapter", linkedMac);
//                    BluetoothPeripheral peripheral = bluetoothCentralManager.getConnectedPeripherals(linkedMac);
//                    Log.d(TAG, "onBluetoothAdapterStateChanged: "+peripheral);;
//                    batch.put(peripheral, peripheralCallback);
//                }
//                bluetoothCentralManager.autoConnectPeripheralsBatch(batch);
            }
            if (BluetoothAdapter.STATE_OFF == state) {
                Log.d(TAG, "BluetoothDisabled");
            }
        }

**Comment by weliem** [comment] 2021-08-31 06:46
Your finding seems to suggest that something doesn't get cleaned up properly when bluetooth is turned off. I will have a look to see if I can reproduce it and fix it.

**Comment by weliem** [comment] 2021-08-31 06:52
Can you provide a log snippet for when it is not working?

**Comment by weliem** [comment] 2021-09-07 05:53
I tried reproducing the issue but I couldn't reproduce it. Please provide more information if you are still having this issue.

**Comment by weliem** [comment] 2021-09-08 17:02
closing issue due to lack of information

**Closed by weliem** 2021-09-08 17:02 UTC
